MACRO( COPYSRC COPY_IN_PATH COPY_IN_FILE COPY_OUT_PATH COPY_OUT_FILE )

  SET( IN_PATH "${COPY_IN_PATH}" )
  SET( OUT_PATH "${COPY_OUT_PATH}" ) 
  SET( IN_FILE "${COPY_IN_FILE}" )
  SET( OUT_FILE "${COPY_OUT_FILE}" )

  MESSAGE(STATUS "Configuring copy action for: ${IN_FILE}" )
  CONFIGURE_FILE( ${CMAKE_CURRENT_SOURCE_DIR}/cmake/copySrc.cmake.in ${CMAKE_CURRENT_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/${OUT_FILE}.cmake @ONLY)
  # add custom target
  ADD_CUSTOM_COMMAND( OUTPUT ${OUT_PATH}/${OUT_FILE}
    COMMAND ${CMAKE_COMMAND} -P ${CMAKE_CURRENT_BINARY_DIR}${CMAKE_FILES_DIRECTORY}/${OUT_FILE}.cmake
    DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/cmake/copySrc.cmake.in ${IN_PATH}/${IN_FILE}
    COMMENT "Copying ${IN_FILE} -> ${OUT_FILE} to binary tree" )
  ADD_CUSTOM_TARGET( COPY_${OUT_FILE} ALL DEPENDS ${OUT_PATH}/${OUT_FILE} )

ENDMACRO( COPYSRC )
